spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_user?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "@root1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

# slf4j日志配置
logging:
  # 配置级别
  level:
    root: info
    #分包配置级别，即不同的目录下可以使用不同的级别
    com.example.project.controller: debug
  config: classpath:logback.xml

